CREATE TABLE IF NOT EXISTS TB_VIAGENS
(
    ID                     BIGINT NOT NULL AUTO_INCREMENT ,
    ID_CARRO               BIGINT ,
    ID_CLIENTE             BIGINT ,
    ID_LOCALIZACAO_ORIGEM  BIGINT ,
    ID_LOCALIZACAO_DESTINO BIGINT ,
    PARTIDA                TIMESTAMP ,
    CHEGADA                TIMESTAMP ,
    STATUS_VIAGEM          INTEGER ,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
