CREATE TABLE IF NOT EXISTS TB_CLIENTES
(
    ID        BIGINT       NOT NULL AUTO_INCREMENT ,
    NOME      VARCHAR(200) NOT NULL ,
    DOCUMENTO INTEGER      NOT NULL ,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT
  INTO TB_CLIENTES (NOME ,DOCUMENTO)
VALUES ('Jose Almeida' ,53214);
INSERT
  INTO TB_CLIENTES (NOME ,DOCUMENTO)
VALUES ('Maria Rita' ,65474);
INSERT
  INTO TB_CLIENTES (NOME ,DOCUMENTO)
VALUES ('Joao da Silva' ,32165);
INSERT
  INTO TB_CLIENTES (NOME ,DOCUMENTO)
VALUES ('Mariana Menezes' ,98532);
INSERT
  INTO TB_CLIENTES (NOME ,DOCUMENTO)
VALUES ('Rita de Cassia' ,54512);
