CREATE TABLE IF NOT EXISTS TB_CARROS
(
    ID               BIGINT       NOT NULL AUTO_INCREMENT ,
    PLACA            VARCHAR(200) NOT NULL ,
    DISPONIVEL       BOOLEAN      NOT NULL ,
    ID_ULTIMA_VIAGEM BIGINT ,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT
  INTO TB_CARROS (PLACA ,DISPONIVEL)
VALUES ('EDC5412' ,1);
INSERT
  INTO TB_CARROS (PLACA ,DISPONIVEL)
VALUES ('DSS3652' ,1);
INSERT
  INTO TB_CARROS (PLACA ,DISPONIVEL)
VALUES ('UJN4432' ,1);
INSERT
  INTO TB_CARROS (PLACA ,DISPONIVEL)
VALUES ('UJM7896' ,1);
INSERT
  INTO TB_CARROS (PLACA ,DISPONIVEL)
VALUES ('ACE1234' ,1);
INSERT
  INTO TB_CARROS (PLACA ,DISPONIVEL)
VALUES ('DER5278' ,1);
