CREATE TABLE IF NOT EXISTS TB_VIAGENS
(
    ID                     BIGINT NOT NULL AUTO_INCREMENT ,
    ID_CARRO               BIGINT ,
    ID_CLIENTE             BIGINT ,
    ID_LOCALIZACAO_ORIGEM  BIGINT ,
    ID_LOCALIZACAO_DESTINO BIGINT ,
    DATA_HORA_SOLICITACAO  TIMESTAMP ,
    DATA_HORA_PARTIDA      TIMESTAMP ,
    DATA_HORA_CHEGADA      TIMESTAMP ,
    STATUS_VIAGEM          INTEGER ,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
