CREATE TABLE IF NOT EXISTS TB_LOCALIZACOES
(
    ID                    BIGINT NOT NULL AUTO_INCREMENT ,
    LONGITUDE             DOUBLE ,
    LATITUDE              DOUBLE ,
    DATA_HORA_LOCALIZACAO TIMESTAMP ,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

